import os
from pathlib import Path
from typing import Dict, Any
from src.utils.file_utils import load_json_file

# Load main configuration
_CONFIG_PATH = Path(__file__).parent.parent.parent / "config" / "main_config.json"
_main_config = load_json_file(_CONFIG_PATH)

class UploaderConfig:
    """Configuration for the Uploader module"""
    
    def __init__(self):
        # Paths from main config
        self.base_data_path = Path(_main_config["base_settings"]["base_data_path"])
        self.output_dir = self.base_data_path / _main_config["paths"]["final_videos_dir"]
        self.log_dir = self.base_data_path / "logs"
        
        # Platform settings
        self.platforms = {
            "youtube": {
                "api_url": "https://www.googleapis.com/upload/youtube/v3/videos",
                "oauth_url": "https://accounts.google.com/o/oauth2/auth",
                "default_category": "27",  # Education
                "default_privacy": "private",
                "max_retries": 5,
                "retry_delay": 5,
                "chunk_size": 1024 * 1024 * 10,  # 10MB chunks
                "timeout": 30
            },
            "tiktok": {
                "api_url": "https://open-api.tiktok.com/share/video/upload/",
                "max_retries": 3,
                "retry_delay": 3,
                "timeout": 20
            },
            "instagram": {
                "api_url": "https://graph.facebook.com/v18.0/",
                "max_retries": 3,
                "retry_delay": 3,
                "timeout": 20,
                "max_duration": 90  # Seconds
            }
        }
        
        # Default metadata templates
        self.metadata_templates = {
            "youtube": {
                "title": "{topic} - Educational Content",
                "description": """{summary}

Key concepts: {keywords}

This content was automatically generated by AutoEd AI.
""",
                "tags": ["education", "learning", "tutorial"]
            },
            "tiktok": {
                "title": "{topic} #education #learning",
                "tags": ["education", "learning", "tutorial"]
            },
            "instagram": {
                "title": "{topic}",
                "caption": """{summary}
#education #learning #tutorial""",
                "tags": ["education", "learning", "tutorial"]
            }
        }

# Singleton config instance
config = UploaderConfig()
